e_shop/stocks/urls.py
from django.urls import path

from e_shop.stocks.views import StocksListView, StockDetailsView, PurchaseCreateView

urlpatterns = [
    path("", StocksListView.as_view(), name="stocks"),
    path("<int:pk>/", StockDetailsView.as_view(), name="stocks-details"),
    path("purchase/<int:pk>/", PurchaseCreateView.as_view(), name="purchase"),
]

e_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("e_shop.auth_users.urls")),
    path("", include("e_shop.e_shop_base.urls")),
    path("about_us/", include("e_shop.about_us.urls")),
    path("events/", include("e_shop.events.urls")),
    path("contacts/", include("e_shop.contacts.urls")),
    path("stocks/", include("e_shop.stocks.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

e_shop/stocks/models.py
from django.db import models
from django.db.models import CASCADE


class Stock(models.Model):
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=50)
    TYPE_CHOICES = [
        ('suit', 'Suit'),
        ('blouse', 'Blouse'),
        ('t-shirt', 'T-Shirt'),
        ('skirt', 'Skirt'),
        ('pants', 'Pants'),
        ('skirt_suit', 'Skirt Suit'),
    ]
    type = models.CharField(max_length=20, choices=TYPE_CHOICES)
    SIZE_CHOICES = [
        ('L', 'Large'),
        ('S', 'Small'),
        ('M', 'Medium'),
        ('XL', 'Extra Large'),
        ('XXL+', 'Double Extra Large+'),
    ]
    size = models.CharField(max_length=10, choices=SIZE_CHOICES)
    FABRIC_CHOICES = [
        ('cotton', 'Cotton'),
        ('polyester', 'Polyester'),
        ('lycra', 'Lycra'),
    ]
    fabric = models.CharField(max_length=20, choices=FABRIC_CHOICES)
    price = models.FloatField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class ImgStocks(models.Model):

    stocks = models.ForeignKey(Stock, on_delete=CASCADE)
    img = models.ImageField(upload_to="stock_img")


class Purchase(models.Model):

    address = models.CharField()
    phone = models.IntegerField()
    email = models.EmailField()
    product = models.ForeignKey(Stock, on_delete=CASCADE)
    completed = models.BooleanField(default=False)

e_shop/stocks/views.py
from django.shortcuts import render
from django.views import generic as view
from django.contrib.auth import mixins as auth_mixins
from e_shop.stocks.models import Stock, Purchase
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy


class StocksListView(view.ListView):
    model = Stock
    template_name = "stocks/stocks.html"


class StockDetailsView(view.DetailView):
    model = Stock
    template_name = "stocks/stock_details.html"


class PurchaseCreateView(auth_mixins.LoginRequiredMixin, view.CreateView):
    model = Purchase
    fields = ["address", "phone"]
    template_name = "stocks/purchase.html"
    success_url = reverse_lazy('stocks')

    def form_valid(self, form):
        product = get_object_or_404(Stock, pk=self.kwargs['pk'])
        form.instance.product = product
        form.instance.email = self.request.user.email
        return super().form_valid(form)

templates/stocks/purchase.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static "css/purchase.css" %}">
    <div class="purchase-cont">
        <form method="post">
            {{ form }}
            {% csrf_token %}
            <button class="purchase-button">Buy</button>
        </form>
    </div>
{% endblock %}

templates/stocks/stock_details.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static "css/stock_details.css" %}">
    <div class="stock-detail-cont">
        <div class="detail-img"><img src="{{ stock.imgstocks_set.first.img.url }}" alt="big-img" class="big-img">
            <div class="little-img-cont">
            {% for imgUrl in stock.imgstocks_set.all %}
                <div>
                    <button class="button-img" onclick="changeImage('{{ imgUrl.img.url }}')">
                        <img src="{{ imgUrl.img.url }}" alt="s-img" class="s-img">
                    </button>
                </div>
            {% endfor %}
            </div>
        </div>
        <div class="context-cont">
            <h1>{{ stock.name }}</h1>
            <h2>{{ stock.description }}</h2>
            <h1>Price: {{ stock.price }}$</h1>
            <button class="buy-button"><a href="{% url "purchase" pk=stock.pk %}">Buy</a></button>
        </div>
    </div>
    <script src="{% static "js/stock_details.js" %}"></script>
{% endblock %}

templates/stocks/stocks.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static "css/stocks.css" %}">
<div class="stocks-cont">
<div class="thead">
<thead>
<h1>Filter stocks</h1>
      <tr>
        <th class="filter-th"><label for="name-filter"></label><input type="text" id="name-filter" placeholder="Enter stock name"></th>
        <th class="filter-th"><label for="price-filter"></label><input type="text" id="price-filter" placeholder="Enter stock max price"></th>
        <th class="filter-th"><label for="type-filter"></label><select id="type-filter">
                <option></option>
                <option value="Suit">Suit</option>
                <option value="Blouse">Blouse</option>
                <option value="T-Shirt">T-Shirt</option>
                <option value="Skirt">Skirt</option>
                <option value="Pants">Pants</option>
                <option value="Skirt Suit">Skirt Suit</option>
            </select></th>
        <th class="filter-th"><label for="size-filter"></label><select id="size-filter">
                <option></option>
                <option value="S">Small</option>
                <option value="M">Medium</option>
                <option value="L">Large</option>
                <option value="XL">Extra Large</option>
                <option value="XXL+">Double Extra Large+</option>
            </select></th>
        <th class="filter-th"><label for="fabric-filter"></label><select id="fabric-filter">
                <option></option>
                <option value="Cotton">Cotton</option>
                <option value="Polyester">Polyester</option>
                <option value="Lycra">Lycra</option>
            </select></th>
      </tr>
</thead>
</div>
<div class="stocks-list">
    {% for stocks in stock_list %}
        <div class="stock-detail">
            <button class="btn-detail">
                <a href="{% url "stocks-details" pk=stocks.pk %}">
                    <img src="{{ stocks.imgstocks_set.first.img.url }}" alt="stock-img" class="img-stock">
                    <h3 class="product-title">{{ stocks.name }}</h3>
                    <p class="product-price">{{ stocks.price|floatformat:2 }}$</p>
                    <p class="product-type">{{ stocks.type }}</p>
                    <p class="product-size">{{ stocks.size }}</p>
                    <p class="product-fabric">{{ stocks.fabric }}</p>
                </a>
            </button>
        </div>
    {% endfor %}
</div>
</div>
    <script src="{% static "js/stocks.js" %}"></script>
{% endblock %}