e_shop/events/urls.py
from django.urls import path

from e_shop.events import views
from e_shop.events.views import EventsListView, EventsDetailsView

urlpatterns = [
    path("list/", EventsListView.as_view(), name="events_list"),
    path("list/<int:pk>", EventsDetailsView.as_view(), name="event_details"),
    path("list/<int:pk>/add/", views.add_comment, name="add_comment"),
]

e_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("e_shop.auth_users.urls")),
    path("", include("e_shop.e_shop_base.urls")),
    path("about_us/", include("e_shop.about_us.urls")),
    path("events/", include("e_shop.events.urls")),
    path("contacts/", include("e_shop.contacts.urls")),
    path("stocks/", include("e_shop.stocks.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

e_shop/events/models.py
from django.db import models
from django.db.models import CASCADE

from e_shop.e_shop_base.models import Profile


class Event(models.Model):

    event_img = models.ImageField(upload_to="event_img")
    title = models.CharField()
    text = models.TextField()
    date = models.DateField()
    link = models.URLField(blank=True, null=True)


class CommentEvent(models.Model):

    comment = models.TextField()
    date_time = models.DateTimeField(auto_now_add=True)
    to_profile = models.ForeignKey(Profile, on_delete=CASCADE)
    to_event = models.ForeignKey(Event, on_delete=CASCADE)

e_shop/events/forms.py
from django import forms

from e_shop.events.models import CommentEvent


class CommentEventForm(forms.ModelForm):

    class Meta:
        model = CommentEvent
        fields = ['comment']

e_shop/events/views.py
from django.shortcuts import render, redirect
from django.views import generic as view

from e_shop.e_shop_base.models import Profile
from e_shop.events.forms import CommentEventForm
from e_shop.events.models import Event


class EventsListView(view.ListView):
    model = Event
    template_name = "events/events_list.html"
    paginate_by = 3


class EventsDetailsView(view.DetailView):
    model = Event
    template_name = "events/event_detail.html"


def add_comment(request, pk):
    if request.method == 'POST':
        form = CommentEventForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.to_event = Event.objects.get(id=pk)
            comment.to_profile = Profile.objects.get(user=request.user)
            comment.save()
            return redirect('events_list')
    else:
        form = CommentEventForm()
    return render(request, 'events/add_comment.html', {'form': form})

templates/events/add_comment.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static "css/add_comment.css" %}">
    <div class="add_comment_form">
        {% if request.user.is_authenticated %}
            <form method="post">
                {{ form.comment }}
                {% csrf_token %}
                <button type="submit">Submit</button>
            </form>
        {% else %}
            <button><a href="{% url "login_user" %}">Need to login</a></button>
        {% endif %}
            <button><a href="{% url "events_list" %}">Back to Events</a></button>
    </div>
{% endblock %}

templates/events/event_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static "css/event_detail.css" %}">
    <div class="event_detail">
        <img src="{{ event.event_img.url }}" alt="detail picture">
        <h1>{{ event.title }}</h1>
        <p>{{ event.text }}</p>
        {% if event.link %}
        <h2>{{ event.link }}</h2>
        {% else %}
        {% endif %}
        <h2>Date: {{ event.date }}</h2>
        <button class="btn1" onclick="showComments()">Show Comments:</button>
        <ul id="comments-section" class="comment-list">
            {% for ev in event.commentevent_set.all %}
                <div class="comment-container">
                    <div class="name-comment">
                        <h1><img class="prof-img" src="{{ ev.to_profile.img.url }}" alt="profile picture">{{ ev.to_profile.first_name }} {{ ev.to_profile.last_name }}</h1>
                        <p>{{ ev.date_time }}</p>
                    </div>
                    <p>{{ ev.comment }}</p>
                </div>
            {% endfor %}
            <button class="btn1" onclick="hideComments()">Hide Comments</button>
        </ul>
        {% if request.user.is_authenticated %}
        <button class="btn1"><a href="{% url "add_comment" pk=event.pk %}">Add comment</a></button>
        {% else %}
        {% endif %}
        <button class="btn1"><a href="{% url "events_list" %}">Back to Events</a></button>
    </div>
    <script src="{% static "js/event_detail.js" %}"></script>
{% endblock %}

templates/events/events_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static "css/events_list.css" %}">
{% for event in event_list %}
    <div class="event_item">
        <img src="{{ event.event_img.url }}" alt="event_img">
        <a href="{% url "event_details" pk=event.pk %}"><h1>{{ event.title }}</h1></a>
    </div>
{% endfor %}
{#    TODO: make different style#}
    <div class="pages">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}&search={{ search }}">&lt;</a>
        {% endif %}
            {{ page_obj.number }} / {{ paginator.num_pages }}
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}&search={{ search }}">&gt;</a>
        {% endif %}
    </div>
{% endblock %}